### PR TITLE
Added &display=swap

### PR DESCRIPTION
**Pull request by mhimon**
...

### CODE REVIEW

**Comment by tasnimAlam** [comment]
@mhimon  content font family does not work if we add this.

**Comment by mhimon** [comment]
Oh! I am also developing block, everything is working fine.

**Comment by tasnimAlam** [comment]
I've changed content font family to Anton. But this is not working.

Link: https://d.pr/v/M9F2Fp

**Comment by mhimon** [comment]
Ok I will check later. Thanks. Check previous PR

**Pull request closed without merging**
